services:
  localstack:
    image: localstack/localstack:4.14.0
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sns,sqs
      - LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT=1
      - DEFAULT_REGION=eu-west-1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker/localstack/init:/etc/localstack/init"
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=Admin456!pwd
    volumes:
      - seq-data:/data
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Admin456!pwd
      MYSQL_DATABASE: issuing
      MYSQL_USER: admin
      MYSQL_PASSWORD: Admin456!pwd
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"

volumes:
  seq-data:
  db_data: