$env:AWS_ACCESS_KEY_ID = "test"
$env:AWS_SECRET_ACCESS_KEY = "test"
$env:AWS_DEFAULT_REGION = "eu-west-1"
$endpoint="http://localhost:4566"
$region="eu-west-1"
$queueUrl="http://sqs.eu-west-1.localhost.localstack.cloud:4566/000000000000/authorization-events-queue"